<?php

/**
 * BaseEmpleador
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $localidad_id
 * @property string $cuit
 * @property string $nombre
 * @property string $domicilio
 * @property date $baja
 * @property integer $sf_guard_user_id
 * @property sfGuardUser $User
 * @property Localidad $Localidad
 * @property Doctrine_Collection $BoletaSindical
 * @property Doctrine_Collection $BoletaFondo
 * 
 * @method integer             getLocalidadId()      Returns the current record's "localidad_id" value
 * @method string              getCuit()             Returns the current record's "cuit" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method string              getDomicilio()        Returns the current record's "domicilio" value
 * @method date                getBaja()             Returns the current record's "baja" value
 * @method integer             getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method sfGuardUser         getUser()             Returns the current record's "User" value
 * @method Localidad           getLocalidad()        Returns the current record's "Localidad" value
 * @method Doctrine_Collection getBoletaSindical()   Returns the current record's "BoletaSindical" collection
 * @method Doctrine_Collection getBoletaFondo()      Returns the current record's "BoletaFondo" collection
 * @method Empleador           setLocalidadId()      Sets the current record's "localidad_id" value
 * @method Empleador           setCuit()             Sets the current record's "cuit" value
 * @method Empleador           setNombre()           Sets the current record's "nombre" value
 * @method Empleador           setDomicilio()        Sets the current record's "domicilio" value
 * @method Empleador           setBaja()             Sets the current record's "baja" value
 * @method Empleador           setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Empleador           setUser()             Sets the current record's "User" value
 * @method Empleador           setLocalidad()        Sets the current record's "Localidad" value
 * @method Empleador           setBoletaSindical()   Sets the current record's "BoletaSindical" collection
 * @method Empleador           setBoletaFondo()      Sets the current record's "BoletaFondo" collection
 * 
 * @package    panaderos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpleador extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empleador');
        $this->hasColumn('localidad_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cuit', 'string', 11, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 11,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('domicilio', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('baja', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Localidad', array(
             'local' => 'localidad_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('BoletaSindical', array(
             'local' => 'id',
             'foreign' => 'empleador_id'));

        $this->hasMany('BoletaFondo', array(
             'local' => 'id',
             'foreign' => 'empleador_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}