<?php

/**
 * BasePagado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $empleador_id
 * @property boolean $tipo
 * @property date $periodo
 * @property date $vencimiento
 * @property date $diadepago
 * @property decimal $pago
 * @property Empleador $Empleador
 * 
 * @method integer   getEmpleadorId()  Returns the current record's "empleador_id" value
 * @method boolean   getTipo()         Returns the current record's "tipo" value
 * @method date      getPeriodo()      Returns the current record's "periodo" value
 * @method date      getVencimiento()  Returns the current record's "vencimiento" value
 * @method date      getDiadepago()    Returns the current record's "diadepago" value
 * @method decimal   getPago()         Returns the current record's "pago" value
 * @method Empleador getEmpleador()    Returns the current record's "Empleador" value
 * @method Pagado    setEmpleadorId()  Sets the current record's "empleador_id" value
 * @method Pagado    setTipo()         Sets the current record's "tipo" value
 * @method Pagado    setPeriodo()      Sets the current record's "periodo" value
 * @method Pagado    setVencimiento()  Sets the current record's "vencimiento" value
 * @method Pagado    setDiadepago()    Sets the current record's "diadepago" value
 * @method Pagado    setPago()         Sets the current record's "pago" value
 * @method Pagado    setEmpleador()    Sets the current record's "Empleador" value
 * 
 * @package    panaderos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePagado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pagado');
        $this->hasColumn('empleador_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('periodo', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('vencimiento', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('diadepago', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('pago', 'decimal', 8, array(
             'type' => 'decimal',
             'notnull' => true,
             'default' => 0,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empleador', array(
             'local' => 'empleador_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}