<?php

/**
 * BaseEmpleado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cuil
 * @property string $nombre
 * @property Doctrine_Collection $EmpleadosSin
 * @property Doctrine_Collection $EmpleadosFon
 * 
 * @method string              getCuil()         Returns the current record's "cuil" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method Doctrine_Collection getEmpleadosSin() Returns the current record's "EmpleadosSin" collection
 * @method Doctrine_Collection getEmpleadosFon() Returns the current record's "EmpleadosFon" collection
 * @method Empleado            setCuil()         Sets the current record's "cuil" value
 * @method Empleado            setNombre()       Sets the current record's "nombre" value
 * @method Empleado            setEmpleadosSin() Sets the current record's "EmpleadosSin" collection
 * @method Empleado            setEmpleadosFon() Sets the current record's "EmpleadosFon" collection
 * 
 * @package    panaderos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpleado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empleado');
        $this->hasColumn('cuil', 'string', 11, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 11,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EmpBolSin as EmpleadosSin', array(
             'local' => 'id',
             'foreign' => 'empleado_id'));

        $this->hasMany('EmpBolFon as EmpleadosFon', array(
             'local' => 'id',
             'foreign' => 'empleado_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}