<?php

/**
 * BaseEmpBolSin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $empleado_id
 * @property integer $boletasindical_id
 * @property decimal $salario
 * @property boolean $sepelio
 * @property Empleado $Empleado
 * @property BoletaSindical $BoletaSindical
 * 
 * @method integer        getEmpleadoId()        Returns the current record's "empleado_id" value
 * @method integer        getBoletasindicalId()  Returns the current record's "boletasindical_id" value
 * @method decimal        getSalario()           Returns the current record's "salario" value
 * @method boolean        getSepelio()           Returns the current record's "sepelio" value
 * @method Empleado       getEmpleado()          Returns the current record's "Empleado" value
 * @method BoletaSindical getBoletaSindical()    Returns the current record's "BoletaSindical" value
 * @method EmpBolSin      setEmpleadoId()        Sets the current record's "empleado_id" value
 * @method EmpBolSin      setBoletasindicalId()  Sets the current record's "boletasindical_id" value
 * @method EmpBolSin      setSalario()           Sets the current record's "salario" value
 * @method EmpBolSin      setSepelio()           Sets the current record's "sepelio" value
 * @method EmpBolSin      setEmpleado()          Sets the current record's "Empleado" value
 * @method EmpBolSin      setBoletaSindical()    Sets the current record's "BoletaSindical" value
 * 
 * @package    panaderos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpBolSin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emp_bol_sin');
        $this->hasColumn('empleado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('boletasindical_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('salario', 'decimal', 8, array(
             'type' => 'decimal',
             'notnull' => true,
             'default' => 0,
             'length' => 8,
             ));
        $this->hasColumn('sepelio', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empleado', array(
             'local' => 'empleado_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('BoletaSindical', array(
             'local' => 'boletasindical_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}