<?php

/**
 * BaseLocalidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $cp
 * @property Doctrine_Collection $Empleador
 * 
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method string              getCp()        Returns the current record's "cp" value
 * @method Doctrine_Collection getEmpleador() Returns the current record's "Empleador" collection
 * @method Localidad           setNombre()    Sets the current record's "nombre" value
 * @method Localidad           setCp()        Sets the current record's "cp" value
 * @method Localidad           setEmpleador() Sets the current record's "Empleador" collection
 * 
 * @package    panaderos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocalidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('localidad');
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('cp', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Empleador', array(
             'local' => 'id',
             'foreign' => 'localidad_id'));
    }
}