<?php

/**
 * BoletaSindicalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BoletaSindicalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BoletaSindicalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BoletaSindical');
    }
}