<?php

/**
 * EmpBolSinTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpBolSinTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpBolSinTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmpBolSin');
    }

//ver empleados bol sindi
public function verEmpleados($id){
$respuesta = Doctrine_Query::create()
   ->select("e.*, p.nombre as nombre,p.cuil as cuil")
   ->from('empbolsin e')
   ->leftJoin('e.Empleado p')
   ->Where('boletasindical_id =?' , "$id")
   ->execute();
return $respuesta;
  }

}
