<?php

/**
 * EmpBolFonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpBolFonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpBolFonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmpBolFon');
    }
}