<?php

/**
 * EmpleadorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpleadorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpleadorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Empleador');
    }

/*
$respuesta = Doctrine_Query::create()
   ->select("concat(p.codigo,' - ',p.descripcion) as plan,n.codigo as codigo,s.suscriptor_id as suscriptor_id,s.id as suscripcion_id,concat(n.apellido,' ',n.nombre) as nombre,s.nro as nro,nro_cuota,suscripcion_id,importe,fvencimiento")
   ->from('cuota c')
   ->leftJoin('c.suscripcion s')
   ->leftJoin('s.suscriptor n')
   ->leftJoin('s.plan p')
   ->Where('c.fvencimiento >=?' , "$anio-$mes-1")
   ->andWhere('c.fvencimiento <=?' , "$anio-$mes-31")
   ->andWhere('c.fpago is null') //sin pagar
   ->andWhere('c.fvencimiento <?' , date('Y-m-d')) //menor a la fecha actual
   ->andWhere("n.activo = 1")
   ->orderBy('suscriptor_id')
   ->addOrderBy('fvencimiento')
   ->execute();
return $respuesta;
*/
public function verSindical($id){
$respuesta = Doctrine_Query::create()
   ->from('BoletaSindical bs')
   ->Where('bs.empleador_id =?' , $id)
   ->orderBy('periodo DESC')
   ->execute();
return $respuesta;
  }

public function verFondo($id){
$respuesta = Doctrine_Query::create()
   ->from('BoletaFondo bf')
   ->Where('bf.empleador_id =?' , $id)
   ->orderBy('periodo DESC')
   ->execute();
return $respuesta;
  }

}
